### ISSUE TITLE
can't run it( 

### ISSUE THREAD

**Issue by dimadoma0123** [peaashmeter/invoke-ai-gui-colab#8]
not into collab and all that tweaks at all,my bad. but really want to try things out from the the artistic side. Can you please lead me through correct installation?  Ive done all steps till the last one. got the ngrok token. but there was something like an error 

>> Scanning Model: Anything_v3_vaefixed
** model Anything_v3_vaefixed could not be loaded: pickle exhausted before seeing STOP
Traceback (most recent call last):
  File "/home/InvokeAI/ldm/invoke/model_cache.py", line 81, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/home/InvokeAI/ldm/invoke/model_cache.py", line 222, in _load_model
    self.scan_model(model_name, weights)
  File "/home/InvokeAI/ldm/invoke/model_cache.py", line 312, in scan_model
    scan_result = scan_file_path(checkpoint)
  File "/usr/local/envs/invokeai/lib/python3.9/site-packages/picklescan/scanner.py", line 366, in scan_file_path
    return scan_bytes(file, path, file_ext)
  File "/usr/local/envs/invokeai/lib/python3.9/site-packages/picklescan/scanner.py", line 300, in scan_bytes
    return scan_pytorch(data, file_id)
  File "/usr/local/envs/invokeai/lib/python3.9/site-packages/picklescan/scanner.py", line 288, in scan_pytorch
    magic = get_magic_number(data)
  File "/usr/local/envs/invokeai/lib/python3.9/site-packages/picklescan/torch.py", line 77, in get_magic_number
    for opcode, args, _pos in genops(data):
  File "/usr/local/envs/invokeai/lib/python3.9/pickletools.py", line 2283, in _genops
    raise ValueError("pickle exhausted before seeing STOP")
ValueError: pickle exhausted before seeing STOP 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   You appear to have a missing or misconfigured model file(s).                   
   The script will now exit and run configure_invokeai.py to help fix the problem.
   After reconfiguration is done, please relaunch invoke.py.                      
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
configure_invokeai is launching....

Loading Python libraries...

Welcome to InvokeAI. This script will help download the Stable Diffusion weight files
and other large models that are needed for text to image generation. At any point you may interrupt
this program and resume later.

** DOWNLOADING DIFFUSION WEIGHTS **
You can download and configure the weights files manually or let this
script do it for you. Manual installation is described at:

https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/

You may download the recommended models (about 10GB total), select a customized set, or
completely skip this step.

Download <r>ecommended models, <a>ll models, <c>ustomized list, or <s>kip this step? [r]: r
** LICENSE AGREEMENT FOR WEIGHT FILES **

By downloading the Stable Diffusion weight files from the official Hugging Face
repository, you agree to have read and accepted the CreativeML Responsible AI License.
The license terms are located here:

   https://huggingface.co/spaces/CompVis/stable-diffusion-license

Accept the above License terms? [y] y
Thank you!

Authenticating to Huggingface
Huggingface token not found in cache.
Token was not found in the environment variable HUGGING_FACE_HUB_TOKEN.
Token was not found in the environment variable HUGGINGFACE_TOKEN.

You may optionally enter your Huggingface token now. InvokeAI *will* work without it, but some functionality may be limited.
See https://invoke-ai.github.io/InvokeAI/features/CONCEPTS/#using-a-hugging-face-concept for more information.

Visit https://huggingface.co/settings/tokens to generate a token. (Sign up for an account if needed).

Paste the token below using Ctrl-Shift-V (macOS/Linux) or right-click (Windows), and/or 'Enter' to continue.
You may re-run the configuration script again in the future if you do not wish to set the token right now.
        
so im got the hugginface token downloaded recommended models and ended up with that:

** Model Installation Successful **

You're all set!

If you installed using one of the automated installation scripts,
execute 'invoke.sh' (Linux/macOS) or 'invoke.bat' (Windows) to
start InvokeAI.

If you installed manually, activate the 'invokeai' environment
(e.g. 'conda activate invokeai'), then run one of the following
commands to start InvokeAI.

Web UI:
    python scripts/invoke.py --web # (connect to http://localhost:9090/)
Command-line interface:
   python scripts/invoke.py

Have fun!
![Снимок экрана 2023-01-30 в 17 56 09](https://user-images.githubusercontent.com/123964287/215532502-c5bd482f-dad9-4b26-bd27-6b02da76137d.png)

**Comment by daveramirez5** [comment]
Same issue here. It seems it started recently, I noticed it 2 days ago.
